// bake-regs.mjs — turn a qemu "info registers" dump into src/snapregs.HC (the
// SetSnapRegs() that seeds hemu's CPU state from the snapshot). Run after each
// capture so the registers always match the RAM dump.
//   node tools/bake-regs.mjs <regs.txt>   (default /tmp/hemusnap/regs6.txt)
import { readFileSync, writeFileSync } from "node:fs";

const path = process.argv[2] || "/tmp/hemusnap/regs6.txt";
const t = readFileSync(path, "latin1");

const g = (re) => { const m = t.match(re); if (!m) throw new Error(`missing ${re}`); return m[1].toLowerCase(); };
const hx = (re) => "0x" + g(re).replace(/^0+(?=.)/, "");

// general regs (reg[] order: RAX RCX RDX RBX RSP RBP RSI RDI R8..R15)
const RAX=hx(/RAX=([0-9a-f]+)/i), RBX=hx(/RBX=([0-9a-f]+)/i), RCX=hx(/RCX=([0-9a-f]+)/i), RDX=hx(/RDX=([0-9a-f]+)/i);
const RSI=hx(/RSI=([0-9a-f]+)/i), RDI=hx(/RDI=([0-9a-f]+)/i), RBP=hx(/RBP=([0-9a-f]+)/i), RSP=hx(/RSP=([0-9a-f]+)/i);
const R8=hx(/R8\s*=([0-9a-f]+)/i), R9=hx(/R9\s*=([0-9a-f]+)/i), R10=hx(/R10=([0-9a-f]+)/i), R11=hx(/R11=([0-9a-f]+)/i);
const R12=hx(/R12=([0-9a-f]+)/i), R13=hx(/R13=([0-9a-f]+)/i), R14=hx(/R14=([0-9a-f]+)/i), R15=hx(/R15=([0-9a-f]+)/i);
const RIP=hx(/RIP=([0-9a-f]+)/i), RFL=hx(/RFL=([0-9a-f]+)/i);
const CR0=hx(/CR0=([0-9a-f]+)/i), CR3=hx(/CR3=([0-9a-f]+)/i), CR4=hx(/CR4=([0-9a-f]+)/i);
const EFER=hx(/EFER=([0-9a-f]+)/i);
// segment bases: "FS =0060 0000000011125628 ..." -> 2nd hex field is the base
const segBase = (s) => "0x" + t.match(new RegExp(`${s}\\s*=[0-9a-f]+\\s+([0-9a-f]+)`, "i"))[1].toLowerCase().replace(/^0+(?=.)/, "");
const segSel  = (s) => "0x" + t.match(new RegExp(`${s}\\s*=([0-9a-f]+)`, "i"))[1].toLowerCase().replace(/^0+(?=.)/, "");
const FSB=segBase("FS"), GSB=segBase("GS"), TRB=segBase("TR"), CS=segSel("CS"), SS=segSel("SS");
// GDT=     <base> <limit> ;  IDT=     <base> <limit>
const gdt = t.match(/GDT=\s+([0-9a-f]+)\s+([0-9a-f]+)/i), idt = t.match(/IDT=\s+([0-9a-f]+)\s+([0-9a-f]+)/i);
const GDTB="0x"+gdt[1].replace(/^0+(?=.)/,""), GDTL="0x"+gdt[2].replace(/^0+(?=.)/,"");
const IDTB="0x"+idt[1].replace(/^0+(?=.)/,""), IDTL="0x"+idt[2].replace(/^0+(?=.)/,"");

const out = `//============================================================================
// snapregs.HC — GENERATED by tools/bake-regs.mjs from ${path}.
// CPU state captured from qemu with the VM PAUSED, so registers match the RAM dump.
//============================================================================
U0 SetSnapRegs()
{
  reg[0]=${RAX};  reg[1]=${RCX};  reg[2]=${RDX};  reg[3]=${RBX};
  reg[4]=${RSP};  reg[5]=${RBP};  reg[6]=${RSI};  reg[7]=${RDI};
  reg[8]=${R8};  reg[9]=${R9};  reg[10]=${R10};  reg[11]=${R11};
  reg[12]=${R12};  reg[13]=${R13};  reg[14]=${R14};  reg[15]=${R15};
  rip=${RIP}; rfl=${RFL};
  cr0=${CR0}; cr3=${CR3}; cr4=${CR4}; msr_efer=${EFER};
  msr_fsbase=${FSB}; msr_gsbase=${GSB};
  gdtr_base=${GDTB}; gdtr_limit=${GDTL}; idtr_base=${IDTB}; idtr_limit=${IDTL};
  g_cs=${CS}; g_ss=${SS}; halted=0; icount=0; g_badop=0;
  // Timer: IRQ0->vec 0x20 (PIC IW2), unmask IRQ0(timer)+IRQ2(cascade), pulse IRQ0.
  pic1_base=0x20; pic2_base=0x28;
  pic1_mask=0xF8; pic2_mask=0xEF; pic1_irr=0; pic2_irr=0; pic1_isr=0; pic2_isr=0;  // unmask IRQ0/1/2 + IRQ12
  pit_div=20000; pit_counter=20000; tsc=0; irq_count=0; hpet_ctr=0;
  // CMOS RTC base (advances with icount); date approximate, time-of-day ticks.
  rtc_idx=0; rtc_base_sec=5819; rtc_dow=3; rtc_day=3; rtc_mon=6; rtc_year=24;
}
`;
writeFileSync("/Users/parkerh/Dev/hemu-wasm/src/snapregs.HC", out);
console.log(`wrote snapregs.HC: RIP=${RIP} RSP=${RSP} RBP=${RBP} FSbase=${FSB} GSbase=${GSB} TRbase=${TRB}`);
